name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          echo "${{ secrets_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 and execute script
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets_EC2_USER }}@${{ secrets_EC2_IP_ADDRESS }} << 'EOF'
            cd ${{ secrets_APP_PATH }}
            git pull
            ./application_start.sh
          EOF

      - name: Clean up
        run: rm -f private_key.pem



