name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run deployment script
        env:
          SSH_PRIVATE_KEY: ${{ SSH_PRIVATE_KEY_KAFSCOPROD }}
          REMOTE_USER: ${{ REMOTE_USER }}
          REMOTE_HOST: ${{ REMOTE_HOST }}
        run: |
          chmod +x ./application_start.sh
          ./application_start.sh
