name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 and execute script
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          sudo ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_IP_ADDRESS << 'EOF'
            cd $APP_PATH
            git pull
            ./application_start.sh
          EOF

      - name: Clean up
        run: rm -f private_key.pem




